# Generated by Django 3.2.5 on 2022-04-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='postiton',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
